print ("Welcome to the tip calculator!")
bill = input("What was the total bill? $")
tip = input("What percenatge tip would you like to give? 10, 12, 15?")
tip_convert = ((int(tip) / int(100)) + 1)
num_people = input("How many people to split the bill?")
tip_amount = (float(bill) / int(num_people)) * (tip_convert)
final_amount = round(tip_amount, 2)
final_amount = "{:.2f}".format(tip_amount)
print (f"Each person should pay: {final_amount}")
